---
title: "Computational Musicology"
author: "Lieve"
date: "2/23/2022"
output:
    flexdashboard::flex_dashboard:
      orientation: columns
      vertical_layout: fill
      storyboard: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(flexdashboard)
library(tidyverse)
library(plotly)
library(spotifyr)
library(ggplot2)
library(dplyr)
```



# Introduction

## Corpus {.tabset}
Sitting in a cafe or restaurant, music has a big influence on the atmosphere. Working in a cafe myself, I use a lot of spotify playlists. During the day it will be in the trend of 'Coffee House', in the evening more jazz and in the late hours a rock party. I want to find out what aspects of this music makes them more enjoyable on different parts of the day. For this I will use the playlists we play at my work and compare these with each other.

This will start with a comparison of genre, which will be very different. The first thing that stood out to me is that one of the playlists contains a whole album, which is not like the other playlists.

# Visualisation

## First graph
For the first plot, I put danceability and energy on the axes. I thought these were two good features to see the difference between the parts of the day.




# Conclusion
